spring:
  application:
    name: product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://47.244.178.203/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2b8
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/